//! TROPIC01 L2 CRC16.
//!
//! Replicated byte-for-byte from libtropic `src/lt_crc16.c`:
//! - polynomial `0x8005`, initial value `0x0000`, no input/output reflection,
//!   final XOR `0x0000`. The library then byte-swaps the 16-bit accumulator
//!   before returning, so the on-wire bytes are `[crc >> 8, crc & 0xFF]`.
//!
//! The accumulator value (pre-swap) equals CRC-16/UMTS, whose canonical check
//! over the ASCII string "123456789" is `0xFEE8`. The returned (swapped) value
//! is therefore `0xE8FE`. The unit tests assert both.

/// CRC-16 generator polynomial used by the TROPIC01 L2 framing.
const POLYNOMIAL: u16 = 0x8005;

/// Folds one data byte into the running CRC accumulator.
///
/// Processes the byte MSB-first, no reflection.
fn crc16_byte(data: u8, crc: u16) -> u16
{
    let mut crc = crc ^ ((data as u16) << 8);
    let mut i = 8;
    while i > 0
    {
        if crc & 0x8000 != 0
        {
            crc = (crc << 1) ^ POLYNOMIAL;
        }
        else
        {
            crc <<= 1;
        }
        i -= 1;
    }
    crc
}

/// Computes the TROPIC01 L2 CRC16 over `data`.
///
/// Returns the 16-bit value already byte-swapped, matching libtropic's
/// `crc16()`. The high byte goes on the wire first.
pub(crate) fn crc16(data: &[u8]) -> u16
{
    let mut crc = 0u16;
    for b in data
    {
        crc = crc16_byte(*b, crc);
    }
    crc.swap_bytes()
}

/// Computes the CRC and returns the two bytes in transmit order, index 0 first.
///
/// The returned `[u8; 2]` goes on the wire in array order: index 0 is the first
/// byte sent (the high byte of the pre-swap accumulator), index 1 follows.
pub(crate) fn crc16_bytes(data: &[u8]) -> [u8; 2]
{
    crc16(data).to_be_bytes()
}

#[cfg(test)]
mod tests
{
    use super::*;

    // Generated by compiling and running libtropic's `crc16()` (see
    // lt_crc16.c) over the same inputs.

    #[test]
    fn check_string_123456789()
    {
        // Canonical CRC-16/UMTS check is 0xFEE8 pre-swap, then libtropic swaps it.
        assert_eq!(crc16(b"123456789"), 0xE8FE);
    }

    #[test]
    fn single_byte_01()
    {
        assert_eq!(crc16(&[0x01]), 0x0580);
        assert_eq!(crc16_bytes(&[0x01]), [0x05, 0x80]);
    }

    #[test]
    fn two_bytes_0100()
    {
        assert_eq!(crc16(&[0x01, 0x00]), 0x0386);
        assert_eq!(crc16_bytes(&[0x01, 0x00]), [0x03, 0x86]);
    }

    #[test]
    fn frame_five_bytes()
    {
        assert_eq!(crc16(&[0x02, 0x03, 0xAA, 0xBB, 0xCC]), 0x592C);
    }

    #[test]
    fn sequence_eight_bytes()
    {
        let v = [0x12, 0x34, 0x56, 0x78, 0x9A, 0xBC, 0xDE, 0xF0];
        assert_eq!(crc16(&v), 0x1F15);
    }

    #[test]
    fn empty_input_is_init_value()
    {
        // No bytes folded -> accumulator stays at init 0x0000, swap is still 0.
        assert_eq!(crc16(&[]), 0x0000);
    }

    #[test]
    fn bytes_match_swapped_value()
    {
        let v = [0x02, 0x03, 0xAA, 0xBB, 0xCC];
        let c = crc16(&v);
        assert_eq!(crc16_bytes(&v), c.to_be_bytes());
    }
}
